# HOAS node constructors — kernel-primitive types, compound-type sugar,
# binding forms (pi/sigma/lam/let), intros, literals, annotation/app/projection,
# descriptions, and the eliminator wrappers that compile via desc-ind adapters.
#
# The macro-derived prelude types (`bool`, `nat`, `listOf`, `sum`) and
# their constructors/introduction forms live in `datatype.nix` because they
# reference generated DataSpec records from the macro layer. Cross-part
# references go through `self.<name>`.
{ self, ... }:

let
  # HOAS variable markers. A marker stands for a bound variable at a specific
  # binding depth (level); `elaborate` converts it to `T.mkVar` with the
  # correct de Bruijn index.
  _hoasTag = "__nix-effects-hoas-marker__";

  levelAsInt = lvl:
    if builtins.isInt lvl then
      if lvl < 0 then null else lvl
    else if builtins.isAttrs lvl && lvl ? _htag then
      if lvl._htag == "level-zero" then 0
      else if lvl._htag == "level-suc" && lvl ? pred then
        let n = levelAsInt lvl.pred; in
        if n == null then null else n + 1
      else null
    else null;

  sameLevelSyntax = l: m:
    let
      li = levelAsInt l;
      mi = levelAsInt m;
    in
      if li != null || mi != null then
        li != null && mi != null && li == mi
      else if builtins.isAttrs l && builtins.isAttrs m then
        if l ? _hoas && m ? _hoas then
          l._hoas == _hoasTag && m._hoas == _hoasTag
          && (l ? level) && (m ? level) && l.level == m.level
        else if l ? _htag && m ? _htag && l._htag == m._htag then
          if l._htag == "level-max" && (l ? lhs) && (l ? rhs) && (m ? lhs) && (m ? rhs) then
            sameLevelSyntax l.lhs m.lhs && sameLevelSyntax l.rhs m.rhs
          else false
        else false
      else false;
in {
  scope = {
    mkMarker = level: { _hoas = _hoasTag; inherit level; };
    isMarker = x: builtins.isAttrs x && x ? _hoas && x._hoas == _hoasTag;

    # Kernel-primitive value types tying the type theory to the
    # underlying Nix value layer. `bool` is generated by `BoolDT`, and
    # `void` is defined further down as `Fin 0`; `unit` remains a
    # kernel primitive whose alias `unitPrim` pins the ⊤-slice I
    # parameter throughout the description machinery.
    string = { _htag = "string"; };
    int_ = { _htag = "int"; };
    float_ = { _htag = "float"; };
    attrs = { _htag = "attrs"; };
    path = { _htag = "path"; };
    function_ = { _htag = "function"; };
    any = { _htag = "any"; };

    bootEq = type: lhs: rhs: { _htag = "boot-eq"; inherit type lhs rhs; };
    bootRefl = { _htag = "boot-refl"; };
    bootJ = type: lhs: motive: base: rhs: eq_:
      { _htag = "boot-j"; inherit type lhs motive base rhs; eq = eq_; };
    eq = type: lhs: rhs: self.eqDT type lhs rhs;
    u = level: { _htag = "U"; inherit level; };

    # `Level` sort and its three constructors at the HOAS surface.
    # Lets users quantify over universes (`forall "k" level (k: ...)`)
    # and build level expressions inline (`u (levelMax k1 (levelSuc k2))`).
    # The `level` field of `u` accepts any of: a Nix-meta `Int` (shimmed
    # via `mkLevelLit` in the kernel), a HOAS Level term built from
    # these combinators, or a kernel `Tm` directly — `elaborate` handles
    # each form via `elaborateLevel`.
    level = { _htag = "level"; };
    levelZero = { _htag = "level-zero"; };
    levelSuc = pred: { _htag = "level-suc"; inherit pred; };
    levelMax = lhs: rhs: { _htag = "level-max"; inherit lhs rhs; };
    # Meta-level integer-to-Level helper. This is not a Level eliminator:
    # it accepts only Nix integers and emits closed Level syntax.
    natToLevel = n:
      if !(builtins.isInt n) then
        throw "hoas.natToLevel: expected a Nix integer"
      else
        builtins.foldl' (acc: _: self.levelSuc acc)
          self.levelZero
          (builtins.genList (x: x) (if n < 0 then 0 else n));

    # Compound types (sugar for nested sigma/sum — carry structural info
    # for elaborateValue).
    # fields : [ { name; type; } ... ] — sorted by name
    record = fields: { _htag = "record"; inherit fields; };
    # maybe = Sum(inner, Unit) — null for Right/Unit, value for Left/inner.
    maybe = inner: { _htag = "maybe"; inherit inner; };
    # branches : [ { tag; type; } ... ] — sorted by tag
    variant = branches: { _htag = "variant"; inherit branches; };

    # Binding forms — take Nix lambda for the body.
    forall = name: domain: bodyFn:
      { _htag = "pi"; inherit name domain; body = bodyFn; };
    sigma = name: fst: sndFn:
      { _htag = "sigma"; inherit name fst; body = sndFn; };
    lam = name: domain: bodyFn:
      { _htag = "lam"; inherit name domain; body = bodyFn; };
    let_ = name: type: val: bodyFn:
      { _htag = "let"; inherit name type val; body = bodyFn; };

    # Intro forms and term combinators. `true_` / `false_` are generated
    # by `BoolDT`; `tt` / `ttPrim` are two names for the kernel-primitive
    # Unit intro.
    pair = fst: snd: { _htag = "pair"; inherit fst snd; };
    refl = { _htag = "refl"; };
    funext = { _htag = "funext"; };

    stringLit = s: { _htag = "string-lit"; value = s; };
    intLit = n: { _htag = "int-lit"; value = n; };
    floatLit = f: { _htag = "float-lit"; value = f; };
    attrsLit = { _htag = "attrs-lit"; };
    pathLit = { _htag = "path-lit"; };
    fnLit = { _htag = "fn-lit"; };
    anyLit = { _htag = "any-lit"; };

    strEq = lhs: rhs: { _htag = "str-eq"; inherit lhs rhs; };
    opaqueLam = nixFn: piHoas:
      { _htag = "opaque-lam"; _fnBox = { _fn = nixFn; }; inherit nixFn piHoas; };
    # Surface `absurd` routes through `absurdFin0`: the HOAS `void` is
    # `app fin zero` (a derived `μ (Fin 0 desc) zero`), and `absurdFin0`
    # discharges a witness of `Fin 0` by no-confusion on `Eq Nat (succ
    # m) zero` via a direct J-transport at motive `natCaseU P Unit`.
    absurd = type: term: self.absurdFin0 type term;
    ann = term: type: { _htag = "ann"; inherit term type; };
    # `annTrusted` — annotation whose body is guaranteed well-typed by
    # construction (e.g., the encoded `spineDesc` for a datatype's `D`
    # field, which is built from kernel-internal encoder lambdas with
    # known polymorphic types). Elaborates to `T.mkAnnTrusted`, which
    # `infer`'s ann rule treats as cache-equivalent — skipping the
    # body re-check that otherwise dominates deep recursive-data CHECK
    # per-layer cost. Internal use only — not exposed via the public
    # `H.*` surface.
    annTrusted = term: type: { _htag = "ann"; inherit term type; trusted = true; };
    app = fn: arg: { _htag = "app"; inherit fn arg; };
    fst_ = pair: { _htag = "fst"; inherit pair; };
    snd_ = pair: { _htag = "snd"; inherit pair; };

    # Eliminators. `ind`/`listElim`/`sumElim` wrap motive/base/step in
    # `let_`-bindings at their required types before the application spine,
    # making motive/step/base inferable (VAR via lookupType) and emitting a
    # `let_ P … let_ B … let_ S … <elim>` Tm shape. The user-facing
    # `boolElim` forwards through `BoolDT.elim`.
    #
    # `k` is a universe level — accepts a Nix-meta `Int` (concrete level
    # baked at macro time), a HOAS Level term (`level`/`levelZero`/
    # `levelSuc`/`levelMax` or a bound `k_var` from `forall "k" level
    # (k_var: …)`), or a kernel `Tm` directly. The level threads into
    # the motive's codomain annotation and into the macro-derived
    # eliminator's `K` slot; `elaborateLevel` normalises the encoding
    # at every level-accepting site (`u`, `desc-arg`, `desc-pi`).
    ind = k: motive: base: step: scrut:
      let
        inherit (self) forall app let_ nat zero succ u NatDT;
        piMotiveTy = forall "_" nat (_: u k);
      in
      let_ "P" piMotiveTy motive (P:
      let_ "B" (app P zero) base (B:
      let_ "S" (forall "kArg" nat (kArg:
                forall "_" (app P kArg) (_: app P (succ kArg)))) step (S:
        app (app (app (app (NatDT.elim k) P) B) S) scrut)));

    # Stable aliases for the kernel-primitive Unit type and its intro.
    # Unit is the bootstrap singleton of the description machinery:
    # ⊤-slice I parameter, retI leaves, and scaffolding sites reference
    # `unitPrim`/`ttPrim` directly. Bool is generated by `BoolDT`; Void
    # and Absurd are derived below from `Fin 0`.
    unitPrim   = { _htag = "unit"; };
    ttPrim     = { _htag = "tt"; };

    # Private bootstrap coproduct for descPlus interpretation. The public
    # `sum`/`inl`/`inr` in `datatype.nix` are generated SumDT forms.
    bootSum = L: R: { _htag = "boot-sum"; inherit L R; };
    bootInl = L: R: v: { _htag = "boot-inl"; inherit L R; term = v; };
    bootInr = L: R: v: { _htag = "boot-inr"; inherit L R; term = v; };
    bootSumElim = left: right: motive: onLeft: onRight: scrut:
      { _htag = "boot-sum-elim"; inherit left right motive onLeft onRight scrut; };

    listElim = k: A: motive: onNil: onCons: scrut:
      let
        inherit (self) forall app let_ listOf nil cons u ListDT;
        piMotiveTy = forall "_" (listOf A) (_: u k);
      in
      let_ "P" piMotiveTy motive (P:
      let_ "N" (app P (nil A)) onNil (N:
      let_ "C" (forall "h" A (hVar:
                forall "t" (listOf A) (tVar:
                forall "_" (app P tVar) (_:
                  app P (cons A hVar tVar))))) onCons (C:
        app (app (app (app (app (ListDT.elim k) A) P) N) C) scrut)));

    sumElimAt = level: k: A: B: motive: onLeft: onRight: scrut:
      let
        inherit (self) forall app let_ sumAt inlAt inrAt u SumDT;
        levelTm = if builtins.isInt level then self.natToLevel level else level;
        piMotiveTy = forall "_" (sumAt levelTm A B) (_: u k);
      in
      let_ "P" piMotiveTy motive (P:
      let_ "L" (forall "a" A (aVar: app P (inlAt levelTm A B aVar))) onLeft (L:
      let_ "R" (forall "b" B (bVar: app P (inrAt levelTm A B bVar))) onRight (R:
        app (app (app (app (app (app (app (SumDT.elim k) levelTm) A) B) P) L) R) scrut)));

    sumElim = k: A: B: motive: onLeft: onRight: scrut:
      self.sumElimAt self.levelZero k A B motive onLeft onRight scrut;

    j = type: lhs: motive: base: rhs: eq_:
      { _htag = "j"; inherit type lhs motive base rhs; eq = eq_; };

    # Propositional truncation. `squash A : U(level-of A)`. Two
    # `squashIntro _` values inhabiting the same `Squash A` are conv-
    # equal (definitional irrelevance). `squashElim A B f x : Squash B`
    # for `f : A → Squash B` and `x : Squash A`; the motive is required
    # to be a `Squash`-typed target.
    squash      = A:          { _htag = "squash";       inherit A; };
    squashIntro = a:          { _htag = "squash-intro"; inherit a; };
    squashElim  = A: B: f: x: { _htag = "squash-elim";  inherit A B f x; };

    # congSuc : Π(a b : Level). Eq Level a b → Eq Level (suc a) (suc b).
    # J on `e` at motive `λx _. Eq Level (suc a) (suc x)`; the base
    # case at x = a is `refl : Eq Level (suc a) (suc a)`.
    congSuc =
      let inherit (self) lam forall ann level bootEq levelSuc bootJ bootRefl;
      in ann
        (lam "a" level (a:
         lam "b" level (b:
         lam "e" (bootEq level a b) (e:
           bootJ level a
             (lam "x" level (x:
                lam "_e" (bootEq level a x) (_:
                  bootEq level (levelSuc a) (levelSuc x))))
             bootRefl
             b
             e))))
        (forall "a" level (a:
         forall "b" level (b:
         forall "_" (bootEq level a b) (_:
           bootEq level (levelSuc a) (levelSuc b)))));

    # maxSucDom : Π(a b : Level). Eq Level (max a b) b → Eq Level (max a (suc b)) (suc b).
    # Lifts a `max-eq-b` bound witness through suc on the right operand.
    # J on `e` at motive `λx _. Eq Level (max a (suc x)) (suc x)`. Base
    # case at x = max a b: convLevel reduces both `max a (suc (max a b))`
    # and `suc (max a b)` to canonical `[{a,1},{b,1}]` (suc-distribution
    # threads the shift outward and dedup keeps the max shift per base),
    # so refl typechecks. Used in descDesc's heterogeneous summands to
    # discharge the inner `descPi` bound witness `Eq Level (max l (suc k)) (suc k)`
    # from `eq_inner : Eq Level (max l k) k`.
    maxSucDom =
      let inherit (self) lam forall ann level bootEq levelSuc levelMax bootJ bootRefl;
      in ann
        (lam "a" level (a:
         lam "b" level (b:
         lam "e" (bootEq level (levelMax a b) b) (e:
           bootJ level (levelMax a b)
             (lam "x" level (x:
                lam "_e" (bootEq level (levelMax a b) x) (_:
                  bootEq level (levelMax a (levelSuc x)) (levelSuc x))))
             bootRefl
             b
             e))))
        (forall "a" level (a:
         forall "b" level (b:
         forall "_" (bootEq level (levelMax a b) b) (_:
           bootEq level (levelMax a (levelSuc b)) (levelSuc b)))));

    # Descriptions: types, constructors, and eliminators.
    #
    # `descI`, `retI`, `recI`, `piI`, `muI` build `Desc I` / `μ I D i`
    # directly. `desc`, `descRet`, `descRec`, `descPi`, `mu` are ⊤-slice
    # aliases: `desc = descI unitPrim`, `mu D i = muI unitPrim D i`, etc. —
    # type-level identities at the ⊤-slice. They pin the I slot to the
    # kernel-primitive unit via `unitPrim` (not the HOAS-surface `unit`,
    # which is itself a derived μ form).
    #
    # `descCon`, `descInd` match kernel arities exactly (3, 5): there is
    # no ⊤-slice alias. At I=⊤, call sites write `self.ttPrim` explicitly
    # at the index position.
    descI = I: { _htag = "desc"; inherit I; };
    desc = self.descI self.unitPrim;
    # Universe-polymorphic forms: `descIAt k I` and `descAt k` produce
    # `desc^k I` / `desc^k ⊤`. The level-omitting `descI`/`desc` default
    # to level 0 in the elaborator (the prelude shape).
    descIAt = k: I: { _htag = "desc"; inherit k I; };
    descAt = k: self.descIAt k self.unitPrim;

    muI = I: D: i: { _htag = "mu"; inherit I D i; };
    mu = D: i: self.muI self.unitPrim D i;

    # ─────────────────────────────────────────────────────────────────
    # Encoded description constructors. Every HOAS-elaborated desc
    # inhabitant flows through these and elaborates to a `mkApp` chain
    # over `encodeDescX_Tm` lambdas — at runtime the value tag is
    # `VDescCon` (encoded `μ⊤(descDesc I k) tt` form), never a primitive
    # `VDescX`. Index type `I` is explicit because the encoders are
    # parametric in I.
    #
    # ⊤-slice convenience aliases (`descRet`, `descRec`, `descPi`,
    # `plus`) bake `I = unitPrim` and (where applicable) `k = 0` /
    # `j = ttPrim` so generated prelude descriptions at the ⊤-slice
    # compose naturally without re-threading I.
    # Indexed callers (`absurdFin0`, `eqDesc`, `conDesc`, `spineDesc`,
    # `encodeTag`) use the full I-explicit forms.
    # ─────────────────────────────────────────────────────────────────
    retI    = I: k: j:    { _htag = "desc-ret-enc"; inherit I k j; };
    descRet = self.retI self.unitPrim 0 self.ttPrim;

    descArg = I: k: S: T: { _htag = "desc-arg-enc"; inherit I k S; body = T; };

    descArgAt = I: l: k: S: T:
      { _htag = "desc-arg-enc"; inherit I k l S; body = T; };

    descArgWithEq = I: l: k: S: eq: T:
      { _htag = "desc-arg-enc"; inherit I k l S eq; body = T; };

    recI    = I: k: j: D: { _htag = "desc-rec-enc"; inherit I k j D; };
    descRec = D: self.recI self.unitPrim 0 self.ttPrim D;

    piI     = I: k: S: f: D: { _htag = "desc-pi-enc"; inherit I k S f D; };
    piIAt   = I: l: k: S: f: D: { _htag = "desc-pi-enc"; inherit I k l S f D; };
    piIWithEq = I: l: k: S: f: eq: D:
      { _htag = "desc-pi-enc"; inherit I k l S f eq D; };

    descPi = k: S: D:
      self.piI self.unitPrim k S
        (self.ann (self.lam "_" S (_: self.ttPrim))
                  (self.forall "_" S (_: self.unitPrim)))
        D;

    descPiAt = l: k: S: D:
      self.piIAt self.unitPrim l k S
        (self.ann (self.lam "_" S (_: self.ttPrim))
                  (self.forall "_" S (_: self.unitPrim)))
        D;

    descPiWithEq = l: k: S: eq: D:
      self.piIWithEq self.unitPrim l k S
        (self.ann (self.lam "_" S (_: self.ttPrim))
                  (self.forall "_" S (_: self.unitPrim)))
        eq D;

    # Lift primitive — Tarski + non-cumulative cross-level transport.
    # `LiftAt l m A : U(m)` is the type of values transported from
    # `A : U(l)` up to `U(m)`, given `l ≤ m`. The bound witness
    # `eq : Eq Level (max l m) m` is auto-emitted as `mkBootRefl` by the
    # elaborator (decided via convLevel's semilattice quotient).
    # Conv collapses `LiftAt l l A ≡ A` (idempotent at equal levels),
    # `lowerAt l m A (liftAt l m A a) ≡ a` (β), and
    # `liftAt l m A (lowerAt l m A x) ≡ x` (η). At `l = m`, both the
    # type and the introducer/eliminator are transparent, so prelude
    # code wrapping at homogeneous levels is no-cost.
    # Auto-witness Lift is syntactic identity at visibly equal levels.
    # Explicit-witness variants keep their proof terms visible.
    LiftAt  = l: m: A:
      if sameLevelSyntax l m then A else { _htag = "lift"; inherit l m A; };
    liftAt  = l: m: A: a:
      if sameLevelSyntax l m then a else { _htag = "lift-intro"; inherit l m A a; };
    lowerAt = l: m: A: x:
      if sameLevelSyntax l m then x else { _htag = "lift-elim"; inherit l m A x; };

    # Explicit-witness variants. Use when `l` and `m` are level-polymorphic
    # binders and `convLevel` cannot decide `refl : Eq Level (max l m) m` —
    # the caller supplies the `eq` term derived in scope (e.g. via
    # `congSuc`/`maxSucDom`). The elaborator emits `T.mkLift l m eq A`
    # rather than auto-injecting `T.mkBootRefl`. For homogeneous `l = m` and
    # convLevel-decidable bounds, prefer `LiftAt`/`liftAt`/`lowerAt` whose
    # elaboration skips the eq HOAS subterm.
    LiftAtWithEq  = l: m: eq: A:    { _htag = "lift";       inherit l m eq A; };
    liftAtWithEq  = l: m: eq: A: a: { _htag = "lift-intro"; inherit l m eq A a; };
    lowerAtWithEq = l: m: eq: A: x: { _htag = "lift-elim";  inherit l m eq A x; };

    descCon = D: i: d: { _htag = "desc-con"; inherit D i d; };

    descInd = D: motive: step: i: scrut:
      { _htag = "desc-ind"; inherit D motive step i scrut; };

    # Kernel-primitive interpretation/All-witness/everywhere-recursor for
    # descriptions (CDMM 2010 §4.2.3 + §6.1, Table 6.2). Each elaborates to
    # a single Tm constructor whose reduction lives in
    # `eval/desc.nix:vInterpDF`/`vAllDF`/`vEverywhereDF`. The `level` /
    # `K` slots accept a Nix-meta `Int`, a HOAS `Level` term, or a kernel
    # `Tm` directly — `elaborate` normalises via `elaborateLevel`.
    #
    #   interpD ℓ I D X i           : U(ℓ)
    #   allD ℓ I D K X M i d        : U(K)
    #   everywhereD ℓ I D K X M ih i d : allD ℓ I D K X M i d
    interpD = level: I: D: X: i:
      { _htag = "interp-d"; inherit level I D X i; };
    allD = level: I: D: K: X: M: i: d:
      { _htag = "all-d"; inherit level I D K X M i d; };
    everywhereD = level: I: D: K: X: M: ih: i: d:
      { _htag = "everywhere-d"; inherit level I D K X M ih i d; };

    # `descElim I k L motive onRet onArg onRec onPi onPlus scrut` —
    # encoded eliminator. `I` is the index type, `k` the universe at
    # which `onArg`/`onPi` bind their sort `S` (matches the encoder
    # encoding), `L` the motive codomain universe. Elaborates to a
    # `mkApp` chain over `encodeDescElimTm`; the kernel runs the
    # cascade over `descDesc I k`'s plus-tree to dispatch on `scrut`'s
    # constructor summand.
    descElim = I: k: L: motive: onRet: onArg: onRec: onPi: onPlus: scrut:
      { _htag = "desc-elim-enc";
        inherit I k L motive onRet onArg onRec onPi onPlus scrut; };

    # First-class binary coproduct of descriptions. `plusI I k A B :
    # Desc^k I` where A, B : Desc^k I share the same index type and
    # universe. `plus` is the ⊤-slice alias at I=⊤, k=0. Both
    # elaborate to encoded `mkApp encodeDescPlusTm I k A B` chains —
    # the resulting `VDescCon` value's interpretation reduces to
    # kernel `Sum (⟦A⟧ X i) (⟦B⟧ X i)` via `interpD`'s encoded-desc view
    # branch, eliminating the commuting-conv obligation on `interp ∘
    # bool-elim` that the Bool-tag-dispatched `descArg bool (boolElim
    # _ A B)` encoding would impose.
    plusI = I: k: A: B: { _htag = "desc-plus-enc"; inherit I k A B; };
    plus  = A: B: self.plusI self.unitPrim 0 A B;

    # Nat-specific equality lemma. Thin wrapper over `j` at type `Nat`;
    # consumed by `absurdFin0` to compose the ret-leaf `em : Eq Nat (succ
    # m) nArg` with `e0 : Eq Nat nArg zero` into `emz : Eq Nat (succ m)
    # zero`.
    transNat = a: b: c: eab: ebc:
      self.bootJ self.nat b
        (self.lam "x" self.nat (x: self.lam "_" (self.bootEq self.nat b x) (_:
          self.bootEq self.nat a x)))
        eab
        c ebc;

    # Fin prelude forwarders onto `FinDT` (defined in
    # `hoas/datatype.nix` via `datatypeI "Fin" nat […]`). The
    # description, type family, constructors, and eliminator all
    # route through the macro-derived fields. Constructor / elim
    # forwarders η-expand to preserve the public Nix-level arity, so
    # `absurdFin0` below and every
    # downstream consumer (`app fin n`, `fzero m`, `fsuc m k`,
    # `finElim P Pz Ps n k`) keeps its surface shape.
    finDesc = self.FinDT.D;
    fin     = self.FinDT.T;
    fzero   = m: self.app self.FinDT.fzero m;
    fsuc    = m: k: self.app (self.app self.FinDT.fsuc m) k;
    finElim = k: P: Pz: Ps: n: x:
      self.app (self.app (self.app (self.app (self.app (self.FinDT.elim k) P) Pz) Ps) n) x;

    # absurdFin0 : (P : U) → Fin 0 → P
    # Fin 0 is vacuous: both constructor payloads carry an `em : Eq (succ m) n`
    # leaf, and at n = 0 combining with the outer `e0 : Eq n zero` gives
    # `emz : Eq (succ m) zero`. The no-confusion step J-transports `tt :
    # Unit` along `emz` at motive `λx _. natCaseU P Unit x`, landing at
    # `Unit` when x ≡ succ m (base case: `tt` inhabits `Unit`) and at `P`
    # when x ≡ zero (the goal). A single J targets `P` directly — no
    # `Void` intermediate is required.
    absurdFin0 = P: x:
      let
        inherit (self)
          lam forall app fst_ snd_
          nat zero succ bootJ natCaseU
          bootEq bootRefl
          muI descInd interpD allD
          bootSum bootSumElim
          descArg retI recI
          finDesc transNat unitPrim ttPrim;

        muFam = lam "i" nat (i: muI nat finDesc i);

        fzeroSum = descArg nat 0 nat (m_: retI nat 0 (succ m_));
        fsucSum  = descArg nat 0 nat (m_: recI nat 0 m_ (retI nat 0 (succ m_)));
        lInterpAt = iArg_: interpD 0 nat fzeroSum muFam iArg_;
        rInterpAt = iArg_: interpD 0 nat fsucSum  muFam iArg_;

        Q = lam "i" nat (iArg: lam "_" (muI nat finDesc iArg) (_:
              forall "_" (bootEq nat iArg zero) (_: P)));

        # noConf m emz : P given emz : Eq Nat (succ m) zero.
        # J at motive `λx _. natCaseU P Unit x` with base `tt : Unit`;
        # result `natCaseU P Unit zero ≡ P`.
        noConf = m: emz:
          bootJ nat (succ m)
            (lam "x" nat (x: lam "_" (bootEq nat (succ m) x) (_:
              app (natCaseU P unitPrim) x)))
            ttPrim
            zero
            emz;

        step = lam "n" nat (nArg:
               lam "d" (interpD 0 nat finDesc muFam nArg) (d:
               lam "_ih" (allD 0 nat finDesc 0 muFam Q nArg d) (_:
                 lam "e0" (bootEq nat nArg zero) (e0:
                   let
                     lInterp = lInterpAt nArg;
                     rInterp = rInterpAt nArg;
                     sumMot = lam "_s" (bootSum lInterp rInterp) (_: P);
                     onInl = lam "r" lInterp (r:
                       let m = fst_ r;
                           em = snd_ r;
                           emz = transNat (succ m) nArg zero em e0;
                       in noConf m emz);
                     onInr = lam "r" rInterp (r:
                       let m = fst_ r;
                           em = snd_ (snd_ r);
                           emz = transNat (succ m) nArg zero em e0;
                       in noConf m emz);
                   in bootSumElim lInterp rInterp sumMot onInl onInr d))));
      in app (descInd finDesc Q step zero x) bootRefl;

    # natCaseU A B : Nat → U — `natCaseU A B zero ≡ A`;
    # `natCaseU A B (succ _) ≡ B`. Implemented as `descInd nat.D` with
    # step dispatching via `bootSumElim` on `d : BootSum (⟦descRet⟧ muFam
    # iArg) (⟦descRec descRet⟧ muFam iArg)` — the inl branch yields A,
    # the inr branch yields B. Used by `vhead` to dispatch the vecElim
    # motive across vnil/vcons (`natCaseU unit A`: vnil target is `unit`,
    # inhabited by `tt`; vcons target is `A`, inhabited by the head
    # element) and by `absurdFin0` to target `P` at `zero` and `Unit` at
    # `succ _` in the no-confusion J-transport. The IH is discarded —
    # discrimination doesn't depend on recursion.
    natCaseU = A: B:
      let
        inherit (self) ann lam forall nat u unitPrim
                        ttPrim mu descInd interpD allD
                        bootSum bootSumElim descRet descRec;
        D = nat.D;
        muFam = lam "_i" unitPrim (iArg: mu D iArg);
        motive = lam "_i" unitPrim (_: lam "_x" (mu D _) (_: u 0));
        lInterpAt = iArg_: interpD 0 unitPrim descRet muFam iArg_;
        rInterpAt = iArg_: interpD 0 unitPrim (descRec descRet) muFam iArg_;
        step = lam "_i" unitPrim (iArg:
               lam "d" (interpD 0 unitPrim D muFam iArg) (d:
               lam "_ih" (allD 0 unitPrim D 1 muFam motive iArg d) (_:
                 let
                   lInterp = lInterpAt iArg;
                   rInterp = rInterpAt iArg;
                 in bootSumElim lInterp rInterp
                      (lam "_s" (bootSum lInterp rInterp) (_: u 0))
                      (lam "_" lInterp (_: A))
                      (lam "_" rInterp (_: B))
                      d)));
      in
      ann (lam "n" nat (n: descInd D motive step ttPrim n))
          (forall "_" nat (_: u 0));

    # Vec prelude forwarders onto `VecDT` (defined in
    # `hoas/datatype.nix` via `datatypePI "Vec" [{A; U₀}] (_: nat) …`).
    # `natPredCase` / `vhead` / `vtail` below still reference
    # `vec` / `vecElim` by name and continue to work unchanged.
    vecDesc = A: self.app self.VecDT.D A;
    vec     = A: self.app self.VecDT.T A;
    vnil    = A: self.app self.VecDT.vnil A;
    vcons   = A: m: x: xs:
      self.app (self.app (self.app (self.app self.VecDT.vcons A) m) x) xs;
    vecElim = k: A: P: Pn: Pc: n: xs:
      self.app (self.app (self.app (self.app (self.app (self.app (self.VecDT.elim k) A) P) Pn) Pc) n) xs;

    # natPredCase A : Nat → U —
    #   `natPredCase A zero ≡ unit`,
    #   `natPredCase A (succ m) ≡ vec A m`.
    # Case-split on Nat whose succ-case return type depends on the
    # predecessor (extracted as `fst_ r` from the plus summand's
    # payload via `bootSumElim` dispatch). Used by `vtail` to build the
    # vecElim motive `P n xs = natPredCase A n` so the vnil branch
    # targets `unit` (filled by `tt`) and the vcons branch targets
    # `vec A m` (filled by the tail). Generalises the `natCaseU`
    # pattern to payload-dependent succ cases.
    natPredCase = A:
      let
        inherit (self) ann lam forall app nat u unitPrim
                        fst_ ttPrim mu descInd interpD allD
                        bootSum bootSumElim descRet descRec vec;
        D = nat.D;
        muFam = lam "_i" unitPrim (iArg: mu D iArg);
        motive = lam "_i" unitPrim (_: lam "_x" (mu D _) (_: u 0));
        vA = vec A;
        lInterpAt = iArg_: interpD 0 unitPrim descRet muFam iArg_;
        rInterpAt = iArg_: interpD 0 unitPrim (descRec descRet) muFam iArg_;
        step = lam "_i" unitPrim (iArg:
               lam "d" (interpD 0 unitPrim D muFam iArg) (d:
               lam "_ih" (allD 0 unitPrim D 1 muFam motive iArg d) (_:
                 let
                   lInterp = lInterpAt iArg;
                   rInterp = rInterpAt iArg;
                 in bootSumElim lInterp rInterp
                      (lam "_s" (bootSum lInterp rInterp) (_: u 0))
                      # zero case — target is `unit`.
                      (lam "_r" lInterp (_: unitPrim))
                      # succ case — r : Σ(pred:μnat tt) (_: Eq ⊤ tt iArg);
                      # target is `vec A pred`.
                      (lam "r" rInterp (r: app vA (fst_ r)))
                      d)));
      in
      ann (lam "n" nat (n: descInd D motive step ttPrim n))
          (forall "_" nat (_: u 0));

    # vtail : (A : U) → (n : Nat) → Vec A (succ n) → Vec A n.
    # Symmetric to `vhead`: uses vecElim with motive `P n xs = natPredCase A n`.
    # At the vnil case the target is `unit` (filled by `tt`, which conv-
    # reduces from `natPredCase A zero`); at the vcons case the target
    # is `vec A m` (conv-reducing from `natPredCase A (succ m)`),
    # inhabited by returning the tail `xs`.
    vtail = A:
      let
        inherit (self) lam app nat succ ttPrim vec vecElim natPredCase;
        vA  = vec A;
        P   = lam "n" nat (n: lam "_xs" (app vA n) (_:
                app (natPredCase A) n));
        Pn  = ttPrim;
        Pc  = lam "m" nat (mVar: lam "_x" A (_: lam "xs" (app vA mVar) (xsVar:
                lam "_ih" (app (natPredCase A) mVar) (_: xsVar))));
      in lam "n" nat (n: lam "xs" (app vA (succ n)) (xs:
           vecElim 0 A P Pn Pc (succ n) xs));

    # vhead : (A : U) → (n : Nat) → Vec A (succ n) → A.
    # The motive `P n xs = natCaseU unit A n` dispatches on n: at the
    # vnil case (n=zero) the target is `unit` (filled by `tt`, which
    # conv-reduces from `natCaseU unit A zero`); at the vcons case
    # (n=succ m) the target is `A` (conv-reducing from
    # `natCaseU unit A (succ m)`), inhabited by returning the head
    # element x. The IH is unused.
    vhead = A:
      let
        inherit (self) lam app nat succ ttPrim unitPrim vec vecElim natCaseU;
        vA  = vec A;
        P   = lam "n" nat (n: lam "_xs" (app vA n) (_:
                app (natCaseU unitPrim A) n));
        Pn  = ttPrim;
        Pc  = lam "m" nat (mVar: lam "x" A (xVar: lam "_xs" (app vA mVar) (_:
                lam "_ih" (app (natCaseU unitPrim A) mVar) (_: xVar))));
      in lam "n" nat (n: lam "xs" (app vA (succ n)) (xs:
           vecElim 0 A P Pn Pc (succ n) xs));

    # Eq-as-description. Public equality is an indexed datatype over a
    # single-constructor retI-only description. The ret leaf itself uses
    # bootstrap identity; these helpers bridge that substrate to EqDT.
    #
    #   eqDesc A a : Desc A         — retI a
    #   eqDT   A a b : U            — μ A (eqDesc A a) b
    #   reflDT A a : eqDT A a a     — descCon (eqDesc A a) a bootRefl
    #
    # The iso with bootstrap identity is witnessed internally:
    # `eqToEqDT` via bootJ transporting reflDT along the equality, and
    # `eqDTToEq` via descInd extracting the retI leaf's witness
    # directly (no bool-dispatch — the description has a single
    # constructor). `eqIsoFwd` / `eqIsoBwd` are the iso proofs: each
    # is an equality between the roundtrip and the identity,
    # discharged by bootJ / descInd reducing both sides to the same
    # canonical form at the bootRefl / descCon cases.
    eqDesc = A: a: self.app (self.app self.EqDT.D A) a;
    eqDT   = A: a: b: self.app (self.app (self.app self.EqDT.T A) a) b;
    reflDT = A: a: self.app (self.app self.EqDT.refl A) a;

    eqToEqDT = A: a: b: e:
      let
        inherit (self) lam bootEq muI eqDesc reflDT bootJ;
        motive = lam "b'" A (b': lam "_e" (bootEq A a b') (_:
                   muI A (eqDesc A a) b'));
      in bootJ A a motive (reflDT A a) b e;

    # `eqDTToEq` routes through descInd with the motive
    # `Q i x = BootEq A a i`; at the sole retI constructor the step's
    # payload `d : BootEq A a i` is the witness, so the step body
    # returns `d` directly. The IH is vacuous (`all` over a retI
    # description is `unit`).
    eqDTToEq = A: a: b: x:
      let
        inherit (self) lam bootEq muI descInd unitPrim eqDesc;
        eD = eqDesc A a;
        Q = lam "i" A (iArg: lam "_x" (muI A eD iArg) (_:
              bootEq A a iArg));
        step = lam "i" A (iArg:
               lam "d" (bootEq A a iArg) (d:
               lam "_ih" unitPrim (_: d)));
      in descInd eD Q step b x;

    # eqIsoFwd : Π(e : BootEq A a b). BootEq (BootEq A a b) (eqDTToEq (eqToEqDT e)) e.
    # bootJ on e reduces the base case to bootRefl.
    eqIsoFwd = A: a: b:
      let
        inherit (self) lam bootEq bootJ bootRefl eqToEqDT eqDTToEq;
        motive = lam "b'" A (b': lam "e'" (bootEq A a b') (e':
                   bootEq (bootEq A a b')
                      (eqDTToEq A a b' (eqToEqDT A a b' e'))
                      e'));
      in lam "e" (bootEq A a b) (e:
           bootJ A a motive bootRefl b e);

    # eqIsoBwd : Π(x : eqDT A a b). BootEq (eqDT A a b) (eqToEqDT (eqDTToEq x)) x.
    # descInd on x with motive
    # `Q i x' = BootEq (μ A eD i) (eqToEqDT (eqDTToEq x')) x'`. At the
    # sole descCon case, eqDTToEq reduces to the payload `d : BootEq A a i`;
    # bootJ transports the bootRefl base case to the general i.
    eqIsoBwd = A: a: b:
      let
        inherit (self) lam bootEq bootJ bootRefl muI unitPrim
                       descCon descInd eqDesc eqToEqDT eqDTToEq;
        eD = eqDesc A a;
        Q = lam "i" A (iArg: lam "x'" (muI A eD iArg) (x':
              bootEq (muI A eD iArg)
                 (eqToEqDT A a iArg (eqDTToEq A a iArg x'))
                 x'));
        jMot = lam "b'" A (b': lam "d'" (bootEq A a b') (d':
                 bootEq (muI A eD b')
                    (eqToEqDT A a b' d')
                    (descCon eD b' d')));
        step = lam "i" A (iArg:
               lam "d" (bootEq A a iArg) (d:
               lam "_ih" unitPrim (_:
                 bootJ A a jMot bootRefl iArg d)));
      in lam "x" (muI A eD b) (x: descInd eD Q step b x);

    boolDesc = self.BoolDT.D;
    bool = self.BoolDT.T;
    true_ = self.BoolDT.true;
    false_ = self.BoolDT.false;

    # boolElim : (k : Level) → (Q : bool → U(k)) → Q true_ → Q false_ → (b : bool) → Q b
    boolElim = k: Q: onT: onF: b:
      let inherit (self) app BoolDT; in
      app (app (app (app (BoolDT.elim k) Q) onT) onF) b;

    # `unit` and `tt` are the kernel bootstrap singleton — Unit is the
    # terminal object of the ambient theory, and the `VTt`/`VNe` unit-η
    # rule at `conv.nix:85-90` gives it a unique-inhabitant-up-to-conv
    # semantics. Retiring Unit would require a meta-level fixpoint
    # mechanism making `Unit = µ Unit unitDesc tt` expressible as a
    # finite Tm; no current phase schedules such a mechanism, so Unit
    # stays primitive, matching CDFM 2010 "Gentle Art of Levitation" §5
    # and every other levitated theory in the literature. The internal
    # `unitPrim` / `ttPrim` aliases above are retained for ⊤-slice
    # aliases and description scaffolding; the surface names resolve to
    # the same kernel Tm.
    unit = self.unitPrim;
    tt = self.ttPrim;

    # `void` reuses the `Fin 0` vacuous family. `absurdFin0` at
    # `combinators.nix` (Fin prelude above) serves as the void
    # eliminator; no separate `voidElim` is introduced. Bare μ-form:
    # `fin` reduces to a descArg-based `μ (Fin 0 desc) zero`, whose
    # inferability is carried by the kernel's `mu` rule routing
    # through desc-* CHECK rules.
    void =
      let inherit (self) app fin zero; in
      app fin zero;
  };
  tests = {};
}
